In [1]:
import numpy as np

In [ ]:
class Hopfield:
    def __init__(self,num_units):
        self.num_units=num_units
        self.weights=np.zeros((num_units,num_units))

    def train(self, patterns):
        num_patterns = len(patterns)
        for p in patterns:
            
            self.weights += np.outer(p, p)
        
        np.fill_diagonal(self.weights, 0)
        self.weights /= num_patterns
    
    def update(self, state):
        
        new_state = state.copy()
        for i in range(self.num_units):
            raw_value = np.dot(self.weights[i], state)
            new_state[i] = 1 if raw_value >= 0 else -1
        return new_state
    
    def predict(self, input_state, max_steps=10):
        
        state = input_state.copy()
        for step in range(max_steps):
            new_state = self.update(state)
            if np.array_equal(new_state, state):
                print(f"Converged in {step+1} steps.")
                break
            state = new_state
        return state

In [3]:
# Define pattern
pattern1 = np.array([1,  1, -1, -1, -1, -1, 1])
pattern2 = np.array([1, -1,  1, -1, 1, -1, 1])
pattern3 = np.array([-1, 1, -1, 1, -1, 1, -1])
pattern4 = np.array([-1, -1, 1, 1, 1, 1, -1])
patterns = [pattern1, pattern2, pattern3, pattern4]

In [5]:
# Initialize NN
num_units=len(pattern1)
hopfield_net=Hopfield(num_units)

In [6]:
hopfield_net.train(patterns)
print(hopfield_net.weights)

[[ 0.  0.  0. -1.  0. -1.  1.]
 [ 0.  0. -1.  0. -1.  0.  0.]
 [ 0. -1.  0.  0.  1.  0.  0.]
 [-1.  0.  0.  0.  0.  1. -1.]
 [ 0. -1.  1.  0.  0.  0.  0.]
 [-1.  0.  0.  1.  0.  0. -1.]
 [ 1.  0.  0. -1.  0. -1.  0.]]


In [7]:
test_pattern = np.array([1, -1, -1, -1, 1, -1, 1])
print("Test Pattern: ",test_pattern)

Test Pattern:  [ 1 -1 -1 -1  1 -1  1]


In [8]:
retrieved_pattern = hopfield_net.predict(test_pattern, max_steps=10)
print("Retrieved pattern:", retrieved_pattern)

Converged in 3 steps.
Retrieved pattern: [ 1 -1  1 -1  1 -1  1]
